import { CommonModule } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import JsBarcode from 'jsbarcode';
import {
  type StockInvoice,
  type StockInvoiceList,
  StockInvoiceService,
} from './stock-invoice-service';

type PrintableBarcodeLabel = {
  title: string;
  code: string;
  subtitle: string;
};

@Component({
  selector: 'app-stock-invoices',
  imports: [CommonModule, FormsModule, RouterLink],
  templateUrl: './stock-invoices.html',
})
export class StockInvoices implements OnInit {
  private router: Router = inject(Router);
  private stockInvoiceService = inject(StockInvoiceService);

  invoices = signal<StockInvoice[]>([]);

  pagination = signal({ limit: 10, offset: 0, total: 0, page: 1, totalPages: 0 });

  filters = {
    invoiceNumber: '',
    invoiceDate: '',
    minAmount: undefined as number | undefined,
    maxAmount: undefined as number | undefined,
    limit: 10,
    page: 1,
    sortField: 'id',
    sortDirection: 'desc' as 'asc' | 'desc',
  };

  loading = false;
  printingInvoiceId: number | null = null;
  error: string | null = null;

  ngOnInit(): void {
    this.loadInvoices();
  }

  get sortValue() {
    return `${this.filters.sortField}:${this.filters.sortDirection}`;
  }

  set sortValue(value: string) {
    const [field, direction] = value.split(':');
    this.filters.sortField = field || 'id';
    this.filters.sortDirection = direction === 'asc' ? 'asc' : 'desc';
  }

  loadInvoices() {
    this.loading = true;
    this.error = null;

    this.stockInvoiceService
      .getAll({
        page: this.filters.page,
        limit: this.filters.limit,
        invoiceNumber: this.filters.invoiceNumber,
        invoiceDate: this.filters.invoiceDate,
        minAmount: this.filters.minAmount,
        maxAmount: this.filters.maxAmount,
        sort: this.sortValue,
      })
      .subscribe({
        next: (res: StockInvoiceList) => {
          this.invoices.set(
            res.data.map((invoice) => ({
              ...invoice,
              totalQty: Number(invoice.totalQty ?? 0),
              totalAmount: Number(invoice.totalAmount ?? 0),
            })),
          );
          this.pagination.set(res.pagination);
          this.loading = false;
        },
        error: (err) => {
          this.error = err.error?.error || 'Failed to load stock invoices';
          this.loading = false;
        },
      });
  }

  applyFilters() {
    this.filters.page = 1;
    this.loadInvoices();
  }

  goToPreviousPage() {
    if (this.filters.page <= 1) {
      return;
    }

    this.filters.page -= 1;
    this.loadInvoices();
  }

  goToNextPage() {
    if (this.filters.page >= this.pagination().totalPages) {
      return;
    }

    this.filters.page += 1;
    this.loadInvoices();
  }

  onLimitChange() {
    this.filters.page = 1;
    this.loadInvoices();
  }

  onSortChange() {
    this.filters.page = 1;
    this.loadInvoices();
  }

  deleteInvoice(invoiceId: number) {
    if (!confirm('Delete this stock invoice?')) {
      return;
    }

    this.stockInvoiceService.delete(invoiceId).subscribe({
      next: () => {
        this.loadInvoices();
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to delete stock invoice';
      },
    });
  }

  printBarcodes(invoiceId: number) {
    this.printingInvoiceId = invoiceId;
    this.error = null;

    // open PDF generated by backend directly in new tab
    // const url = this.stockInvoiceService.getBarcodePdfUrl(invoiceId);
    // const popup = window.open(url, '_blank');
    // if (!popup) {
    //   this.error = 'Popup blocked. Please allow popups and try again.';
    // }

    // open barcode print window
    this.stockInvoiceService.getById(invoiceId).subscribe({
      next: (invoice) => {
        this.openBarcodePrintWindow(this.buildBarcodeLabels(invoice));
      },
      error: (err) => {
        this.error = err.error?.error || 'Failed to load stock invoice for barcode printing';
      },
      complete: () => {
        this.printingInvoiceId = null;
      },
    });
  }

  private buildBarcodeLabels(invoice: StockInvoice): PrintableBarcodeLabel[] {
    const labels: PrintableBarcodeLabel[] = [];

    for (const item of invoice.items ?? []) {
      const barcodeValue = String(item.gtn ?? item.productCode ?? '').trim();
      if (!barcodeValue) {
        continue;
      }

      const qty = Math.max(1, Math.round(Number(item.qty ?? 1)));
      const title = String(item.productName ?? item.productCode ?? 'Product');
      const subtitle = `Rs. ${Number(item.unitPrice ?? 0).toFixed(2) ?? '0.00'}`;

      for (let i = 0; i < qty; i += 1) {
        labels.push({ title, code: barcodeValue, subtitle });
      }
    }

    return labels;
  }

  private openBarcodePrintWindow(labels: PrintableBarcodeLabel[]) {
    const printWindow = window.open('', '_blank', 'width=1024,height=768');
    // console.log('Print window opened:', printWindow?.document.documentElement.innerHTML);
    if (!printWindow) {
      this.error = 'Popup blocked. Please allow popups and try again.';
      return;
    }

    const labelsHtml = labels
      .map((label) => {
        const barcodeSvg = this.generateBarcodeSvg(label.code);
        return `<section class="label">
            <div class="title">${this.escapeHtml(label.title)}</div>
            <div class="barcode">${barcodeSvg}</div>
            <div class="code">${this.escapeHtml(label.code)}</div>
            <div class="subtitle">${this.escapeHtml(label.subtitle)}</div>
          </section>`;
      })
      .join('');

    const htmlContent = `<!doctype html>
  <html>
  <head>
    <meta charset="utf-8" />
    <title>Barcode Print</title>
    <style>
      @page {
        size: 50mm 30mm;
        margin: 0;
      }
  
      * {
        box-sizing: border-box;
      }
  
      body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
      }
  
      .label {
        width: 50mm;
        height: 30mm;
        padding: 2.5mm;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        page-break-after: always;
        break-after: page;
      }
  
      .title {
        font-size: 9px;
        line-height: 1.2;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
  
      .barcode svg {
        width: 100%;
        height: 10mm;
        display: block;
      }
  
      .code {
        margin-top: 1mm;
        font-size: 9px;
        text-align: center;
        letter-spacing: 0.5px;
      }
  
      .subtitle {
        font-size: 8px;
        color: #444;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
    </style>
  </head>
  <body>${labelsHtml}</body>
  </html>`;

    printWindow.document.open();
    printWindow.document.close();
    printWindow.document.documentElement.innerHTML = htmlContent;
    printWindow.focus();
    setTimeout(() => printWindow.print(), 100);
  }

  private generateBarcodeSvg(value: string) {
    const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
    JsBarcode(svg, value, {
      format: 'CODE128',
      displayValue: false,
      margin: 0,
      width: 1.5,
      height: 44,
    });
    return svg.outerHTML;
  }

  private escapeHtml(value: string) {
    return value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
  }
}
