@baseUrl=http://localhost:4000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoiYnNlZXRoYSIsImlhdCI6MTc2OTA0NTM2NCwiZXhwIjoxNzY5NjUwMTY0fQ.5pjAJP1fni3Ga4JixsoJQCJroVizxIZ0cXu85oYpBLc

### Get all categories
GET {{baseUrl}}/categories
Authorization: Bearer {{token}}


### Create Category
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "",
  "description": "Investments for a short term period",
}


###
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Long term investment",
  "description": "Investments for a long term period",
  "type": "Asset"
}

###
POST {{baseUrl}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Personal expenses",
  "description": "Personal expenses",
  "type": "Expense"
}
