@baseUrl=http://localhost:4000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGJhbGEiLCJpYXQiOjE3NjYwMjM3OTksImV4cCI6MTc2NjYyODU5OX0.MAluOIEI9_IJs3B0LHSRqMJXMEBFglu7xj0lpOMyI5Q

### Get all registers
GET {{baseUrl}}/registers
Authorization: Bearer {{token}}


### Create register
POST {{baseUrl}}/registers
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Seetha personal expenses",
  "description": "Seetha expenses",
  "categoryId": 3
}
